[package]
name = "day9_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[target.'cfg(target_os="macos")'.dependencies]
swift-bridge = "0.1.0"

[target.'cfg(target_os="macos")'.build-dependencies]
swift-bridge-build = "0.1.0"
