[package]
name = "day9_rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0"
divan = "0"

[[bench]]
name = "criterion"
harness = false

[[bench]]
name = "divan"
harness = false
